### DISCUSSION TITLE
Custom environment on docker install

### DISCUSSION THREAD

**Discussion by 3v1lm1ky** [deepfence/ThreatMapper#690] [General]
Hi,

I have some question. I have try implement threatmapper to our cloud. But I have some problem when setup with docker.
can I'm use external elasticsearch? I have node setup properly for central logging using elasticsearch but when I try connecting from threatmapper service I get problem. FYI, my central logging using SSL. Any eviroment variable to use SSL?

```
version: "3.7"
services:
  deepfence-topology:
    container_name: deepfence-topology
    image: ${IMAGE_REPOSITORY:-deepfenceio}/deepfence_discovery_ce:${DF_IMG_TAG:-1.4.1}
    ulimits:
      core: 0
    networks:
      - deepfence_net
    environment:
      - CHECKPOINT_DISABLE=1
      - DF_PROG_NAME=discovery
      - ELASTICSEARCH_SCHEME=https
      - ELASTICSEARCH_HOST=<ip address>
      - ELASTICSEARCH_PORT=<port (9200)>
      - ELASTICSEARCH_USER=<username>
      - ELASTICSEARCH_PASSWORD=<password>
      - REDIS_HOST=deepfence-redis
      - REDIS_PORT=6379
      - REDIS_DB_NUMBER=0
    ports:
      - "127.0.0.1:8004:8004"
    restart: on-failure
    command: topology
    logging:
      driver: "json-file"
      options:
````

I got this error when running

`INFO: 2022/11/24 08:25:32.650144 Get "https://XXX.XXX.XXX.XXX:9200/_msearch": x509: cannot validate certificate for XXX.XXX.XXX.XXX because it doesn't contain any IP SANs`
