### ISSUE TITLE
Agent can't access control plane

### ISSUE THREAD

**Issue by mozt** [deepfence/ThreatMapper#484]
**Describe the bug**
I have installed the control plane (Version 1.3.0) in k8s via the helm chart, and publish it via project contour Ingress controller, witch works only with namebased virtual hosting.
I can't make the agent on a separate vm to work with the control plane, cause it seems that the agent try to make the API requests using the IP address instead of the hostname. Because of this the namebased virtualhosting in project contour doesnt work and the agent cant reach the control plane.

**To Reproduce**
- Install control plane from helm chart
- Publish it with contour httpproxy:
```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: treatmapper-tls
spec:
  virtualhost:
    fqdn: treatmapper.demo
    tls:
      passthrough: true
  tcpproxy:
    services:
      - name: deepfence-router
        port: 443
  routes:
    - services:
      - name: deepfence-router
        port: 80
```
- Start a agent on a separete VM with:
```bash
docker run -dit --cpus=".2" --name=deepfence-agent --restart on-failure --pid=host --net=host \
  --privileged=true -v /sys/kernel/debug:/sys/kernel/debug:rw -v /var/log/fenced \
  -v /var/run/docker.sock:/var/run/docker.sock -v /:/fenced/mnt/host/:ro \
  -e USER_DEFINED_TAGS="" -e MGMT_CONSOLE_URL="treatmapper.demo" -e MGMT_CONSOLE_PORT="443" \
  -e DEEPFENCE_KEY="KEY" -e LOG_LEVEL="debug"\
  deepfenceio/deepfence_agent_ce:1.3.0
```

**Expected behavior**
The agent can communicate with control plane, using the hostname in requests

**Screenshots**
I can see this in agent logs (inside the container in /var/log/fenced/discovery.logfile):
```log
<probe> DEBU: 2022/07/08 06:36:53.613158 background /proc reader: full pass took 264.715148ms
<probe> DEBU: 2022/07/08 06:36:53.613208 background /proc reader: new rate limit period 500ms
<probe> ERRO: 2022/07/08 06:37:00.107353 Error fetching app details: Get "https://10.121.0.30:443/topology-api": read tcp 10.121.0.127:2428->10.121.0.30:443: read: connection reset by peer
<probe> DEBU: 2022/07/08 06:37:03.247119 docker container: collecting stats for 8795da4c7741d5b2b0fa738ef235463eaa5f0e7a6afcc2d1277062b0787de182
<probe> DEBU: 2022/07/08 06:37:03.364350 docker container: stopped collecting stats for 8795da4c7741d5b2b0fa738ef235463eaa5f0e7a6afcc2d1277062b0787de182
```
Where 10.121.0.30 is the IP of DNS treatmapper.demo.

**Components/Services affected**

- [ ] UI/Frontend
- [ ] API/Backend
- [x] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**
