### ISSUE TITLE
Add all elasticsearch config parameters to secrets in console helm chart

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/ThreatMapper#658]
Add following fields to [this](https://github.com/deepfence/ThreatMapper/blob/v1.4.1/deployment-scripts/helm-charts/deepfence-console/templates/configmaps/es_secrets.yaml#L4-L5) secret

https://github.com/deepfence/ThreatMapper/blob/v1.4.1/deployment-scripts/helm-charts/deepfence-console/values.yaml#L68-L70
```
  elasticsearch:
    scheme: "http"
    host: deepfence-es
    port: "9200"
```

Similarly add for redis parameters.
