### ISSUE TITLE
Helmchart - PodAnnotations support

### ISSUE THREAD

**Issue by dhaugli** [deepfence/ThreatMapper#818]
**Additional context**
We would like to have helm chart support for Pod annotations, this has multiple advantages but in our use case it is related to Vault webhook configuration, so that we can store Threatmappers secret in Vault and Threatmapper can access then from Vault, to do this we use PodAnnotations. 

**Describe the solution you'd like**
In our Helmrelease file through fluxCD it could look something like this:

```
values:
  podAnnotations:
    vault.security.banzaicloud.io/vault-role: deepfence
  image:
    tag: 1.4.1
  clusterName: "threatmapper-cluster"
  namespace: default
  serviceAccountName: deepfence-console
  db:
    #createDbSecret: false
    postgresUserDb:
      host: vault:secret/data/deepfence#deepfence-console-postgres-host
      port: "5432"
      user: vault:secret/data/deepfence#deepfence-console-postgres-user
      password: vault:secret/data/deepfence#deepfence-console-postgres-password
      dbname: vault:secret/data/deepfence#deepfence-console-postgresdatabase-name
      sslmode: "require"
```

**Describe alternatives you've considered**

Use clear text password, not an option for us considering our corporate security policy or sealed secret, but that is a bit more of a hassle. 

**Components/Services**

- [ ] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [X ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ X] Other HelmChart
